# Generated by Django 4.1.3 on 2023-04-26 15:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_deskbooking_roombooking_alter_access_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='key',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='userconfig',
            unique_together={('user', 'key')},
        ),
    ]
