# Generated by Django 4.2.2 on 2023-06-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_systemconfig_id_alter_systemconfig_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='height',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='orientation',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='pos_x',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='pos_y',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='width',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
    ]
