# Generated by Django 4.2.2 on 2023-06-16 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_room_height_room_orientation_room_pos_x_room_pos_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='is_maintainer',
            field=models.BooleanField(default=False),
        ),
    ]
