# Generated by Django 4.2.2 on 2023-06-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_access_is_maintainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaykey',
            name='title',
            field=models.CharField(default='Unknown Display', max_length=191),
            preserve_default=False,
        ),
    ]
