# Generated by Django 4.2.2 on 2023-07-05 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_displaykey_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaykey',
            name='list_view',
            field=models.BooleanField(default=False),
        ),
    ]
